### PR TITLE
merge master of erik into master of anudanan

### PR DESCRIPTION
**Pull request by anudanan**

### CODE REVIEW

**Comment by eriksl** [comment]
What's the purpose of this?

**Comment by anudanan** [comment]
I don´t know why this pull request comes to you. I have merged your changes with the github GUI into my fork and these pull request came automatically.

Is it a better way to delete my fork and making a  new one?

**Comment by anudanan** [comment]
I´ve deleted my fork and will make a  new one. I think that is a better way

Now my fork is a new copy of your  master. Thanks for merging and cleanup some  whitespaces and comment lines

**Comment by eriksl** [comment]
The usual way to prepare a PR is like this:

- clone original repo (with git) or fork it (github)
- create a branch for your PR
- apply your changes to the branch
- have your PR applied
- remove your own branch (local and remote)
- do an update (like git pull) and your local repository is completely synchronised
- if you want to do another PR, you can repeat from step 2.

I've never found a reason to completely remove a fork or clone, git is very resiliant and almost always you can get back to some known point.

**Comment by anudanan** [comment]
my local repo is a clone of my fork in github

Pushs from my local to my github works fine
But on github a merge from your master to my master (after your last changes) goes over the pullrequest (i haven´t found an other way) and then you see the pullrequest on your side which I don´t want to have

I haven´t delete my local repo. After deleting the fork and creating a new I can easily pull your last changes to my local repo. I see the conflicts and solve it.

local git is easier to use than  github with merges.

**Comment by anudanan** [comment]
one additional info

after your close of my pullrequest than github had gave me an offer to delete my fork. It looks like for me that it is normal to delete a github fork after a successful pullrequest

**Comment by eriksl** [comment]
No the usual procedure is to use a branch and then remove the branch.

**Comment by anudanan** [comment]
I will see how it works in future ;-)
Now I have a fork and a work branch on it. The same conent as on my local system

**Pull request closed without merging**
